src/java/com/senac/bean/Stream.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.senac.bean;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author Mateus
 */
@Entity
@Table(name = "stream")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Stream.findAll", query = "SELECT s FROM Stream s"),
    @NamedQuery(name = "Stream.findByIdStream", query = "SELECT s FROM Stream s WHERE s.idStream = :idStream"),
    @NamedQuery(name = "Stream.findByTitulo", query = "SELECT s FROM Stream s WHERE s.titulo = :titulo"),
    @NamedQuery(name = "Stream.findByDataInicio", query = "SELECT s FROM Stream s WHERE s.dataInicio = :dataInicio"),
    @NamedQuery(name = "Stream.findByDataTermino", query = "SELECT s FROM Stream s WHERE s.dataTermino = :dataTermino"),
    @NamedQuery(name = "Stream.findByDataCriacao", query = "SELECT s FROM Stream s WHERE s.dataCriacao = :dataCriacao"),
    @NamedQuery(name = "Stream.findByUrl", query = "SELECT s FROM Stream s WHERE s.url = :url"),
    @NamedQuery(name = "Stream.findByChave", query = "SELECT s FROM Stream s WHERE s.chave = :chave")})
public class Stream implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id_stream")
    private Integer idStream;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 50)
    @Column(name = "titulo")
    private String titulo;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 50)
    @Column(name = "data_inicio")
    private String dataInicio;
    @Size(max = 50)
    @Column(name = "data_termino")
    private String dataTermino;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 50)
    @Column(name = "data_criacao")
    private String dataCriacao;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 50)
    @Column(name = "url")
    private String url;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 100)
    @Column(name = "chave")
    private String chave;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "idStream")
    private List<Evento> eventoList;

    public Stream() {
    }

    public Stream(Integer idStream) {
        this.idStream = idStream;
    }

    public Stream(Integer idStream, String titulo, String dataInicio, String dataCriacao, String url, String chave) {
        this.idStream = idStream;
        this.titulo = titulo;
        this.dataInicio = dataInicio;
        this.dataCriacao = dataCriacao;
        this.url = url;
        this.chave = chave;
    }

    public Integer getIdStream() {
        return idStream;
    }

    public void setIdStream(Integer idStream) {
        this.idStream = idStream;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getDataInicio() {
        return dataInicio;
    }

    public void setDataInicio(String dataInicio) {
        this.dataInicio = dataInicio;
    }

    public String getDataTermino() {
        return dataTermino;
    }

    public void setDataTermino(String dataTermino) {
        this.dataTermino = dataTermino;
    }

    public String getDataCriacao() {
        return dataCriacao;
    }

    public void setDataCriacao(String dataCriacao) {
        this.dataCriacao = dataCriacao;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getChave() {
        return chave;
    }

    public void setChave(String chave) {
        this.chave = chave;
    }

    @XmlTransient
    public List<Evento> getEventoList() {
        return eventoList;
    }

    public void setEventoList(List<Evento> eventoList) {
        this.eventoList = eventoList;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idStream != null ? idStream.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Stream)) {
            return false;
        }
        Stream other = (Stream) object;
        if ((this.idStream == null && other.idStream != null) || (this.idStream != null && !this.idStream.equals(other.idStream))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.senac.bean.Stream[ idStream=" + idStream + " ]";
    }
    
}

src/java/com/senac/mb/EventoMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.senac.mb;

import com.senac.bean.Evento;
import java.util.List;

/**
 *
 * @author Mateus
 */
public class EventoMB {
    
    private Evento evento;
    private EventoMB eventoMB;

    public EventoMB() {
    
        evento = new Evento();
        eventoMB = new EventoMB();
    }
    
    public void editar(Evento evento) {

    }

    public void limpar() {

    }

    public List<Evento> lista() {

        return null;
    }

    public String salvar() {
        return null;
    }

    public String excluir() {
        return null;
    }

    public String pesquisar() {
        return null;
    }

    public Evento getUsuario() {
        return evento;
    }

    public void setUsuario(Evento evento) {

    }
}

web/jsf/criarEvento.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    template="templates/tpl_menu_principal.xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="interno">
        <ui:insert name="menu" /><br />
        <div align="center">
            <p:growl id="msgs" showDetail="true" />

            <h:panelGrid columns="2" cellpadding="3">
            Informe o título de sua transmissão:
            <h:inputText id="tituloBroadcast" value="#{eventoStreamingMB.eventoo.tituloEvento}"  required="true" requiredMessage="Campo Título é obrigatório"/>
            Informe a descrição de sua transmissão:
            <h:inputText id="descricaoBroadcast" value="#{eventoStreamingMB.eventoo.descricaoEvento}" required="true" requiredMessage="Campo descrição é obrigatório"/>
            Informe o título do video:
            <h:inputText id="tituloVideo" value="#{eventoStreamingMB.eventoo.tituloStream}" required="true" requiredMessage="Campo Título é obrigatório"/>
            Informe a descrição do video:
            <h:inputText id="descricaoVideo" value="#{eventoStreamingMB.eventoo.descricaoStream}" required="true" requiredMessage="Campo descrição é obrigatório"/>
            <p:outputLabel for="dateStart" value="Data de Início:" />
            <p:calendar id="dateStart" value="#{eventoStreamingMB.eventoo.dataInicio}" required="true" pattern="MM/dd/yyyy HH:mm:ss" mindate="#{eventoStreamingMB.minDate}" maxdate="01/01/2018"/>
            <p:outputLabel for="dateEnd" value="Data de Término" />
            <p:calendar id="dateEnd" value="#{eventoStreamingMB.eventoo.dataTermino}" required="true" pattern="MM/dd/yyyy HH:mm:ss" mindate ="#{eventoStreamingMB.setMinEndDate(eventoStreamingMB.minDate)}" maxdate="01/01/2018" />
            Usuario:
            <h:selectOneMenu value="#{eventoStreamingMB.eventoo.idUsuario}" 
                             immediate="true" >  
                <f:converter converterId="UsuarioConverter"/>
                <f:selectItems value="#{usuarioMB.lista()}" var="reg" itemLabel="#{reg.nome}" itemValue="#{reg}"/>  
            </h:selectOneMenu>
            Categorias:
            <h:selectOneMenu value="#{eventoStreamingMB.eventoo.idCategoria}" 
                             immediate="true" >  
                <f:converter converterId="CategoriaConverter"/>
                <f:selectItems value="#{categoriaMB.lista()}" var="reg" itemLabel="#{reg.nome}" itemValue="#{reg}"/>  
            </h:selectOneMenu>
            </h:panelGrid>
            
            
            <h:commandButton value="Ok" action="#{eventoStreamingMB.salvar()}" class="button round small success"/>
        </div>
    </ui:define>
    
</ui:composition>

web/jsf/editarCategoria.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    template="templates/tpl_menu_principal.xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="interno">
        <ui:insert name="menu" /><br />
        <div align="center">
            <h:inputHidden value="#{categoriaMB.categoria.idCategoria}"/>
            <h:panelGrid columns="2">
                Título: <h:inputText id="titulo" value="#{categoriaMB.categoria.nome}" required="true" requiredMessage="Campo Título é obrigatório"/>
                Tags: <h:inputTextarea value="#{categoriaMB.categoria.tag}"/>
            </h:panelGrid> 
            <ul class="button-group radius">
                <li><h:commandButton value="Salvar" action="#{categoriaMB.salvar()}" class="button small" /></li>
                <li><h:commandButton value="Limpar" action="#{categoriaMB.limpar()}" class="button small"/></li>
            </ul>
        </div>
        <script type="text/javascript">
        $(window).ready(function(){
                $('#titulo').focus();
            });
        </script>
    </ui:define>
    
</ui:composition>

web/jsf/editarEvento.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    template="templates/tpl_menu_principal.xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="interno">
        <ui:insert name="menu" /><br />
        <div align="center">
            <h:panelGrid columns="2">
                Título: <h:inputText id="titulo" required="true" requiredMessage="Campo Título é obrigatório"/>
                Data: <h:inputText required="true" requiredMessage="Campo Data é obrigatório"/>
                Hora: <h:inputText required="true" requiredMessage="Campo Hora é obrigatório"/>
                Categoria: <h:selectOneMenu required="Campo Categoria é obrigatório">
                    <f:selectItem itemValue="1" itemLabel="Selecione..." />
                    <f:selectItem itemValue="2" itemLabel="C#" />
                    <f:selectItem itemValue="3" itemLabel="C++" />
                    <f:selectItem itemValue="4" itemLabel="JAVA" />
                    <f:selectItem itemValue="5" itemLabel="JAVA SCRIPT" />
                    <f:selectItem itemValue="6" itemLabel="JAVA WEB" />
                    <f:selectItem itemValue="7" itemLabel="PHP" />
                    <f:selectItem itemValue="8" itemLabel="PYTHON" />
                    <f:selectItem itemValue="9" itemLabel="Outros" />
                    
                </h:selectOneMenu>
                Tipo: <h:selectOneRadio>
                    <f:selectItem itemValue="0" itemLabel="Público" />
                    <f:selectItem itemValue="1" itemLabel="Privado" />
                    
                </h:selectOneRadio>
            </h:panelGrid> 
            <ul class="button-group radius">
                <li><h:commandButton value="Salvar" action="eventos" class="button small" /></li>
                <li><h:commandButton value="Excluir" action="eventos" class="button small"  immediate="true"/></li>
                <li><h:commandButton value="Limpar" class="button small" immediate="true"/></li>
            </ul>
        </div>
        <script type="text/javascript">
        $(window).ready(function(){
                $('#titulo').focus();
            });
        </script>
    </ui:define>
    
</ui:composition>

web/jsf/editarUsuario.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    template="templates/tpl_menu_principal.xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="interno">
        <ui:insert name="menu" /><br />
        <div align="center">
            <h:inputHidden value="#{usuarioMB.usuario.idUsuario}" />
            <h:panelGrid columns="2">
                Nome: <h:inputText id="name" required="true" value="#{usuarioMB.usuario.nome}" requiredMessage="Campo Nome é obrigatório"/>
                Sobrenome: <h:inputText required="true" value="#{usuarioMB.usuario.sobrenome}" requiredMessage="Campo Sobrenome é obrigatório"/>                
                Email: <h:inputText required="true" value="#{usuarioMB.usuario.email}" requiredMessage="Campo Email é obrigatório"/>
                Senha: <h:inputText required="true" value="#{usuarioMB.usuario.senha}" requiredMessage="Campo Senha é obrigatório"/>
            </h:panelGrid> 
            <ul class="button-group radius">
                <li><h:commandButton value="Salvar" action="#{usuarioMB.salvar()}" class="button small"/></li>
                <li><h:commandButton value="Limpar" class="button small" action="#{usuarioMB.limpar()}"/></li>
            </ul>
        </div>
        <script type="text/javascript">
        $(window).ready(function(){
                $('#name').focus();
            });
        </script>
    </ui:define>
    
</ui:composition>

web/jsf/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    template="templates/tpl_principal.xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
    xmlns:pm="http://primefaces.org/mobile"
    xmlns:p="http://primefaces.org/ui">
    
    <ui:define name="interno">
        
        <div class="large-12 columns corpo_single_page">
            
            <div align="center" class="large-12 columns corpo_banner">
                
                <div class="large-5 columns banner_texto">
                    <br/>
                    <h1 align="left">Share Knowledge</h1>
                    <h6 align="left">Compartilhando Conhecimento</h6>
                    <h4 align="left"><h:graphicImage value="/images/banner/icon.png" class="icon"></h:graphicImage>Grupo de Estudos</h4>
                    <h4 align="left"><h:graphicImage value="/images/banner/icon.png" class="icon"></h:graphicImage>Vídeo Aulas</h4>
                    <h4 align="left"><h:graphicImage value="/images/banner/icon.png" class="icon"></h:graphicImage>Reuniões em Tempo Real</h4>
                    <h4 align="left"><h:graphicImage value="/images/banner/icon.png" class="icon"></h:graphicImage>Reforço de Professores</h4>
            
                </div>
                
                <div class="large-7 columns banner_div">
                    <br/>
                    <p:commandLink value="Cadastre-se" action="editarUsuario" class="button round success"/>    
                    
                    <h:graphicImage value="/images/banner/banner01.png" height="600" class="banner_img"></h:graphicImage>
                </div>
            </div>
        </div>
        
        <div class="large-12 columns corpo_single_page">
            
            <div align="center" class="large-12 columns corpo_banner">

                <div align="left" class="large-12 columns">
                    <h2>O que é?</h2>
                </div>
                
                <div class="large-4 columns">
                    <br/>
                    <h:graphicImage value="/images/conferencia.png"></h:graphicImage>
                </div>
                <div class="large-7 columns">
                    <br/>
                <h5 align="left">O aplicativo Share Knowledge tem o objetivo de ser um portal online colaborativo, contendo um repositório de atividades desenvolvidas em um determinado assunto, por meio de grupos de estudo, possibilitando aos integrantes e aos usuários da aplicação o compartilhamento e a troca de experiências, visando à disseminação da informação na área de TI.  Contendo a finalidade de acesso facilitado à informação e ao conhecimento, disseminação da informação e informações compartilhadas, com o reconhecimento via LinkedIn para palestrantes.</h5>
                
                </div>  
            </div>
        </div>
    </ui:define>
    
</ui:composition>

web/jsf/listarCategorias.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    template="templates/tpl_menu_principal.xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

    <ui:define name="interno">
       <ui:insert name="menu" />
       
       <br />
       <div class="row">
        <div class="large-12 columns">
            <div class="row collapse postfix-radius">
              <div class="small-9 columns">
                  
                  <h:inputText value="#{categoriaMB.pesquisa}" pt:placeholder="faça sua busca..." immediate="false"/>
              </div>
              <div class="small-3 columns">
                  <h:commandButton value="pesquisar" action="#{categoriaMB.pesquisar()}" class="button default postfix"/>
              </div>
            </div>
        </div>
       
        <br />    
       
        <div class="large-12 columns">
       <h:commandButton value="Novo" action="editarCategoria" class="button tiny radius" />
       <h:commandButton value="Limpar" action="#{categoriaMB.limparTudo()}" class="button tiny radius" />
       </div>
       </div>
       <p:dataTable id="dataTable" var="reg"
                    value="#{categoriaMB.lista()}"
                    paginator="true"
                    rows="5"
                    paginatorPosition="top">
           <p:column width="5%">
               <f:facet name="header">
                   <h:outputText value="Cod"/>
               </f:facet>
               <center>
               <h:outputText value="#{reg.idCategoria}"/>
               </center>
           </p:column>
           <p:column>
               <f:facet name="header">
                   <h:outputText value="Nome"/>
               </f:facet>
               <h:outputText value="#{reg.nome}"/>
           </p:column>
           <p:column>
               <f:facet name="header">
                   <h:outputText value="Tag"/>
               </f:facet>
               <h:outputText value="#{reg.tag}"/>
           </p:column>
           <p:column width="18%">
               <f:facet name="header">  
                   <h:outputText value="Ação" />  
               </f:facet>  
               <center>
                    <p:commandButton style="margin-top: 8%" value="Editar" ajax="false" actionListener="#{categoriaMB.editar(reg)}" action="editarCategoria" />
                    <p:commandButton style="margin-top: 8%" value="Excluir" ajax="false" actionListener="#{categoriaMB.excluir(reg)}"/>
               </center>
           </p:column>
       </p:dataTable>       
              
    </ui:define>
    
</ui:composition>

web/jsf/listarEventos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    template="templates/tpl_menu_principal.xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

    <ui:define name="interno">
       <ui:insert name="menu" />
        <br />

         <div class="large-12 columns">
             <div class="row collapse postfix-radius">
               <div class="large-9 columns">
                   <h:inputText pt:placeholder="faça sua busca..." immediate="false"/>
               </div>
               <div class="large-3 columns">
                   <h:commandButton value="pesquisar" class="button default postfix"/>
               </div>
             </div>
         </div>

         <br />    

        <div class="large-12 columns">
             <h:commandButton value="Novo" action="criarEvento" class="button tiny radius" />
        </div>
       
        
            <div class="large-9 columns"> 
                <p:dataGrid var="event" value="#{listarStreaming.listarVideos()}" columns="3" id="event">

                    <iframe width="230" height="150" src="https://www.youtube.com/embed/#{event.id}" frameborder="0" allowfullscreen="true" ></iframe>

                </p:dataGrid>
            </div>
        <!-- INÍCIO TABELA MAIS VISTOS -->         
            <aside class="large-3 columns">
                <p:dataGrid var="event1" value="#{listarStreaming.listarVideos()}" columns="1" 
                id="event1">

                     <iframe width="300" height="200" src="https://www.youtube.com/embed/#{event1.id}" frameborder="0" allowfullscreen="true" ></iframe>

                </p:dataGrid>
            </aside>
        
        <!-- FINAL TABELA MAIS VISTOS -->
    </ui:define>
    
</ui:composition>

web/jsf/listarUsuarios.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    template="templates/tpl_menu_principal.xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

    <ui:define name="interno">
       <ui:insert name="menu" />
       
       <br />
       <div class="row">
        <div class="large-12 columns">
            <div class="row collapse postfix-radius">
              <div class="small-9 columns">
                
                  <h:inputText value="#{usuarioMB.pesquisa}" pt:placeholder="faça sua busca..." immediate="false"/>
              </div>
              <div class="small-3 columns">
                  <h:commandButton value="pesquisar" action="#{usuarioMB.pesquisar()}" class="button default postfix"/>
                
              </div>
            </div>
        </div>
       
        <br />    
       
        <div class="large-12 columns">
            <h:commandButton value="Novo" action="editarUsuario" class="button tiny radius" />
            <h:commandButton value="Limpar" action="#{usuarioMB.limparTudo()}" class="button tiny radius" />
        </div>
       </div>
       <p:dataTable id="dataTable" var="reg"
                    value="#{usuarioMB.lista()}"
                    paginator="true"
                    paginatorPosition="top"
                    rows="5"
                    >
           <p:column width="5%">
                <f:facet name="header">
                    
                    <h:outputText value="Cod"/>
                </f:facet>
               <center>
                <h:outputText value="#{reg.idUsuario}"/>
               </center>
           </p:column>
           <p:column>
               <f:facet name="header">
                   <h:outputText value="Nome"/>
               </f:facet>
               <h:outputText value="#{reg.nome}"/>
           </p:column>
           <p:column>
               <f:facet name="header">
                   <h:outputText value="Sobrenome"/>
               </f:facet>
               <h:outputText value="#{reg.sobrenome}"/>
           </p:column>
           <p:column>
               <f:facet name="header">
                   <h:outputText value="Email"/>
               </f:facet>
               <h:outputText value="#{reg.email}"/>
           </p:column>
           <p:column>
               <f:facet name="header">
                   <h:outputText value="Senha"/>
               </f:facet>
               <h:outputText value="#{reg.senha}"/>
           </p:column>
           <p:column width="18%">
               <f:facet name="header">  
                   <h:outputText value="Ação" />
               </f:facet>  
               <center>
                   <p:commandButton style="margin-top: 8%" value="Editar" ajax="false"  actionListener="#{usuarioMB.editar(reg)}" action="editarUsuario" />
                   <p:commandButton style="margin-top: 8%" value="Excluir" ajax="false" actionListener="#{usuarioMB.excluir(reg)}"/>
               </center>
           </p:column>  
           
       </p:dataTable>       
       
    </ui:define>
    
</ui:composition>


web/jsf/stream.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    template="templates/tpl_menu_principal.xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="interno">
       <ui:insert name="menu" />
       
       <br />
       
       <div class="large-8 columns">
           <h:graphicImage value="/images/stream.gif"></h:graphicImage>
       </div>
       <div class="small-4 columns">
       <h:panelGrid columns="1" class="chat">
           
       </h:panelGrid>
       
            <h:inputText id="chat" class="chat_campo" pt:placeholder="Digite sua Pergunta aqui..."></h:inputText>
       </div>
       
       <h1>Aprendendo Java</h1>
       
       <br></br>
        
    </ui:define>
    
</ui:composition>